spring.application.name=demo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=b2203090-6690-41a8-9d87-807e27ec4cdb
spring.cloud.azure.active-directory.profile.tenant-id=22eab006-c3be-4576-a05f-ffddfc6c7e2d
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/22eab006-c3be-4576-a05f-ffddfc6c7e2d/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/22eab006-c3be-4576-a05f-ffddfc6c7e2d/discovery/v2.0/keys